export const baseUrl = import.meta.env.VITE_BACKEND_URL;
 
export const countries = [
    { name: 'Åland Islands', code: 'AX', dial_code: '+358', flag: '🇦🇽', image: 'https://flagcdn.com/w320/ax.png' },
    { name: 'Afghanistan', code: 'AF', dial_code: '+93', flag: '🇦🇫', image: 'https://flagcdn.com/w320/af.png' },
    { name: 'Albania', code: 'AL', dial_code: '+355', flag: '🇦🇱', image: 'https://flagcdn.com/w320/al.png' },
    { name: 'Algeria', code: 'DZ', dial_code: '+213', flag: '🇩🇿', image: 'https://flagcdn.com/w320/dz.png' },
    { name: 'American Samoa', code: 'AS', dial_code: '+1684', flag: '🇦🇸', image: 'https://flagcdn.com/w320/as.png' },
    { name: 'Andorra', code: 'AD', dial_code: '+376', flag: '🇦🇩', image: 'https://flagcdn.com/w320/ad.png' },
    { name: 'Angola', code: 'AO', dial_code: '+244', flag: '🇦🇴', image: 'https://flagcdn.com/w320/ao.png' },
    { name: 'Anguilla', code: 'AI', dial_code: '+1264', flag: '🇦🇮', image: 'https://flagcdn.com/w320/ai.png' },
    { name: 'Antarctica', code: 'AQ', dial_code: '+672', flag: '🇦🇶', image: 'https://flagcdn.com/w320/aq.png' },
    { name: 'Antigua and Barbuda', code: 'AG', dial_code: '+1268', flag: '🇦🇬', image: 'https://flagcdn.com/w320/ag.png' },
    { name: 'Argentina', code: 'AR', dial_code: '+54', flag: '🇦🇷', image: 'https://flagcdn.com/w320/ar.png' },
    { name: 'Armenia', code: 'AM', dial_code: '+374', flag: '🇦🇲', image: 'https://flagcdn.com/w320/am.png' },
    { name: 'Aruba', code: 'AW', dial_code: '+297', flag: '🇦🇼', image: 'https://flagcdn.com/w320/aw.png' },
    { name: 'Australia', code: 'AU', dial_code: '+61', flag: '🇦🇺', image: 'https://flagcdn.com/w320/au.png' },
    { name: 'Austria', code: 'AT', dial_code: '+43', flag: '🇦🇹', image: 'https://flagcdn.com/w320/at.png' },
    { name: 'Azerbaijan', code: 'AZ', dial_code: '+994', flag: '🇦🇿', image: 'https://flagcdn.com/w320/az.png' },
    { name: 'Bahamas', code: 'BS', dial_code: '+1242', flag: '🇧🇸', image: 'https://flagcdn.com/w320/bs.png' },
    { name: 'Bahrain', code: 'BH', dial_code: '+973', flag: '🇧🇭', image: 'https://flagcdn.com/w320/bh.png' },
    { name: 'Bangladesh', code: 'BD', dial_code: '+880', flag: '🇧🇩', image: 'https://flagcdn.com/w320/bd.png' },
    { name: 'Barbados', code: 'BB', dial_code: '+1246', flag: '🇧🇧', image: 'https://flagcdn.com/w320/bb.png' },
    { name: 'Belarus', code: 'BY', dial_code: '+375', flag: '🇧🇾', image: 'https://flagcdn.com/w320/by.png' },
    { name: 'Belgium', code: 'BE', dial_code: '+32', flag: '🇧🇪', image: 'https://flagcdn.com/w320/be.png' },
    { name: 'Belize', code: 'BZ', dial_code: '+501', flag: '🇧🇿', image: 'https://flagcdn.com/w320/bz.png' },
    { name: 'Benin', code: 'BJ', dial_code: '+229', flag: '🇧🇯', image: 'https://flagcdn.com/w320/bj.png' },
    { name: 'Bermuda', code: 'BM', dial_code: '+1441', flag: '🇧🇲', image: 'https://flagcdn.com/w320/bm.png' },
    { name: 'Bhutan', code: 'BT', dial_code: '+975', flag: '🇧🇹', image: 'https://flagcdn.com/w320/bt.png' },
    { name: 'Bolivia (Plurinational State of)', code: 'BO', dial_code: '+591', flag: '🇧🇴', image: 'https://flagcdn.com/w320/bo.png' },
    { name: 'Bonaire, Sint Eustatius and Saba', code: 'BQ', dial_code: '+599', flag: '🇧🇶', image: 'https://flagcdn.com/w320/bq.png' },
    { name: 'Bosnia and Herzegovina', code: 'BA', dial_code: '+387', flag: '🇧🇦', image: 'https://flagcdn.com/w320/ba.png' },
    { name: 'Botswana', code: 'BW', dial_code: '+267', flag: '🇧🇼', image: 'https://flagcdn.com/w320/bw.png' },
    { name: 'Bouvet Island', code: 'BV', dial_code: '+47', flag: '🇧🇻', image: 'https://flagcdn.com/w320/bv.png' },
    { name: 'Brazil', code: 'BR', dial_code: '+55', flag: '🇧🇷', image: 'https://flagcdn.com/w320/br.png' },
    { name: 'British Indian Ocean Territory', code: 'IO', dial_code: '+246', flag: '🇮🇴', image: 'https://flagcdn.com/w320/io.png' },
    { name: 'Brunei Darussalam', code: 'BN', dial_code: '+673', flag: '🇧🇳', image: 'https://flagcdn.com/w320/bn.png' },
    { name: 'Bulgaria', code: 'BG', dial_code: '+359', flag: '🇧🇬', image: 'https://flagcdn.com/w320/bg.png' },
    { name: 'Burkina Faso', code: 'BF', dial_code: '+226', flag: '🇧🇫', image: 'https://flagcdn.com/w320/bf.png' },
    { name: 'Burundi', code: 'BI', dial_code: '+257', flag: '🇧🇮', image: 'https://flagcdn.com/w320/bi.png' },
    { name: 'Cabo Verde', code: 'CV', dial_code: '+238', flag: '🇨🇻', image: 'https://flagcdn.com/w320/cv.png' },
    { name: 'Cambodia', code: 'KH', dial_code: '+855', flag: '🇰🇭', image: 'https://flagcdn.com/w320/kh.png' },
    { name: 'Cameroon', code: 'CM', dial_code: '+237', flag: '🇨🇲', image: 'https://flagcdn.com/w320/cm.png' },
    { name: 'Canada', code: 'CA', dial_code: '+1', flag: '🇨🇦', image: 'https://flagcdn.com/w320/ca.png' },
    { name: 'Cayman Islands', code: 'KY', dial_code: '+1345', flag: '🇰🇾', image: 'https://flagcdn.com/w320/ky.png' },
    { name: 'Central African Republic', code: 'CF', dial_code: '+236', flag: '🇨🇫', image: 'https://flagcdn.com/w320/cf.png' },
    { name: 'Chad', code: 'TD', dial_code: '+235', flag: '🇹🇩', image: 'https://flagcdn.com/w320/td.png' },
    { name: 'Chile', code: 'CL', dial_code: '+56', flag: '🇨🇱', image: 'https://flagcdn.com/w320/cl.png' },
    { name: 'China', code: 'CN', dial_code: '+86', flag: '🇨🇳', image: 'https://flagcdn.com/w320/cn.png' },
    { name: 'Christmas Island', code: 'CX', dial_code: '+61', flag: '🇨🇽', image: 'https://flagcdn.com/w320/cx.png' },
    { name: 'Cocos (Keeling) Islands', code: 'CC', dial_code: '+61', flag: '🇨🇨', image: 'https://flagcdn.com/w320/cc.png' },
    { name: 'Colombia', code: 'CO', dial_code: '+57', flag: '🇨🇴', image: 'https://flagcdn.com/w320/co.png' },
    { name: 'Comoros', code: 'KM', dial_code: '+269', flag: '🇰🇲', image: 'https://flagcdn.com/w320/km.png' },
    { name: 'Congo', code: 'CG', dial_code: '+242', flag: '🇨🇬', image: 'https://flagcdn.com/w320/cg.png' },
    { name: 'Congo (Democratic Republic of the)', code: 'CD', dial_code: '+243', flag: '🇨🇩', image: 'https://flagcdn.com/w320/cd.png' },
    { name: 'Cook Islands', code: 'CK', dial_code: '+682', flag: '🇨🇰', image: 'https://flagcdn.com/w320/ck.png' },
    { name: 'Costa Rica', code: 'CR', dial_code: '+506', flag: '🇨🇷', image: 'https://flagcdn.com/w320/cr.png' },
    { name: 'Côte d\'Ivoire', code: 'CI', dial_code: '+225', flag: '🇨🇮', image: 'https://flagcdn.com/w320/ci.png' },
    { name: 'Croatia', code: 'HR', dial_code: '+385', flag: '🇭🇷', image: 'https://flagcdn.com/w320/hr.png' },
    { name: 'Cuba', code: 'CU', dial_code: '+53', flag: '🇨🇺', image: 'https://flagcdn.com/w320/cu.png' },
    { name: 'Curaçao', code: 'CW', dial_code: '+599', flag: '🇨🇼', image: 'https://flagcdn.com/w320/cw.png' },
    { name: 'Cyprus', code: 'CY', dial_code: '+357', flag: '🇨🇾', image: 'https://flagcdn.com/w320/cy.png' },
    { name: 'Czech Republic', code: 'CZ', dial_code: '+420', flag: '🇨🇿', image: 'https://flagcdn.com/w320/cz.png' },
    { name: 'Denmark', code: 'DK', dial_code: '+45', flag: '🇩🇰', image: 'https://flagcdn.com/w320/dk.png' },
    { name: 'Djibouti', code: 'DJ', dial_code: '+253', flag: '🇩🇯', image: 'https://flagcdn.com/w320/dj.png' },
    { name: 'Dominica', code: 'DM', dial_code: '+1767', flag: '🇩🇲', image: 'https://flagcdn.com/w320/dm.png' },
    { name: 'Dominican Republic', code: 'DO', dial_code: '+1', flag: '🇩🇴', image: 'https://flagcdn.com/w320/do.png' },
    { name: 'Ecuador', code: 'EC', dial_code: '+593', flag: '🇪🇨', image: 'https://flagcdn.com/w320/ec.png' },
    { name: 'Egypt', code: 'EG', dial_code: '+20', flag: '🇪🇬', image: 'https://flagcdn.com/w320/eg.png' },
    { name: 'El Salvador', code: 'SV', dial_code: '+503', flag: '🇸🇻', image: 'https://flagcdn.com/w320/sv.png' },
    { name: 'Equatorial Guinea', code: 'GQ', dial_code: '+240', flag: '🇬🇶', image: 'https://flagcdn.com/w320/gq.png' },
    { name: 'Eritrea', code: 'ER', dial_code: '+291', flag: '🇪🇷', image: 'https://flagcdn.com/w320/er.png' },
    { name: 'Estonia', code: 'EE', dial_code: '+372', flag: '🇪🇪', image: 'https://flagcdn.com/w320/ee.png' },
    { name: 'Ethiopia', code: 'ET', dial_code: '+251', flag: '🇪🇹', image: 'https://flagcdn.com/w320/et.png' },
    { name: 'Falkland Islands (Malvinas)', code: 'FK', dial_code: '+500', flag: '🇫🇰', image: 'https://flagcdn.com/w320/fk.png' },
    { name: 'Faroe Islands', code: 'FO', dial_code: '+298', flag: '🇫🇴', image: 'https://flagcdn.com/w320/fo.png' },
    { name: 'Fiji', code: 'FJ', dial_code: '+679', flag: '🇫🇯', image: 'https://flagcdn.com/w320/fj.png' },
    { name: 'Finland', code: 'FI', dial_code: '+358', flag: '🇫🇮', image: 'https://flagcdn.com/w320/fi.png' },
    { name: 'France', code: 'FR', dial_code: '+33', flag: '🇫🇷', image: 'https://flagcdn.com/w320/fr.png' },
    { name: 'French Guiana', code: 'GF', dial_code: '+594', flag: '🇬🇫', image: 'https://flagcdn.com/w320/gf.png' },
    { name: 'French Polynesia', code: 'PF', dial_code: '+689', flag: '🇵🇫', image: 'https://flagcdn.com/w320/pf.png' },
    { name: 'French Southern Territories', code: 'TF', dial_code: '+262', flag: '🇹🇫', image: 'https://flagcdn.com/w320/tf.png' },
    { name: 'Gabon', code: 'GA', dial_code: '+241', flag: '🇬🇦', image: 'https://flagcdn.com/w320/ga.png' },
    { name: 'Gambia', code: 'GM', dial_code: '+220', flag: '🇬🇲', image: 'https://flagcdn.com/w320/gm.png' },
    { name: 'Georgia', code: 'GE', dial_code: '+995', flag: '🇬🇪', image: 'https://flagcdn.com/w320/ge.png' },
    { name: 'Germany', code: 'DE', dial_code: '+49', flag: '🇩🇪', image: 'https://flagcdn.com/w320/de.png' },
    { name: 'Ghana', code: 'GH', dial_code: '+233', flag: '🇬🇭', image: 'https://flagcdn.com/w320/gh.png' },
    { name: 'Gibraltar', code: 'GI', dial_code: '+350', flag: '🇬🇮', image: 'https://flagcdn.com/w320/gi.png' },
    { name: 'Greece', code: 'GR', dial_code: '+30', flag: '🇬🇷', image: 'https://flagcdn.com/w320/gr.png' },
    { name: 'Greenland', code: 'GL', dial_code: '+299', flag: '🇬🇱', image: 'https://flagcdn.com/w320/gl.png' },
    { name: 'Grenada', code: 'GD', dial_code: '+1473', flag: '🇬🇩', image: 'https://flagcdn.com/w320/gd.png' },
    { name: 'Guadeloupe', code: 'GP', dial_code: '+590', flag: '🇬🇵', image: 'https://flagcdn.com/w320/gp.png' },
    { name: 'Guam', code: 'GU', dial_code: '+1671', flag: '🇬🇺', image: 'https://flagcdn.com/w320/gu.png' },
    { name: 'Guatemala', code: 'GT', dial_code: '+502', flag: '🇬🇹', image: 'https://flagcdn.com/w320/gt.png' },
    { name: 'Guernsey', code: 'GG', dial_code: '+44', flag: '🇬🇬', image: 'https://flagcdn.com/w320/gg.png' },
    { name: 'Guinea', code: 'GN', dial_code: '+224', flag: '🇬🇳', image: 'https://flagcdn.com/w320/gn.png' },
    { name: 'Guinea-Bissau', code: 'GW', dial_code: '+245', flag: '🇬🇼', image: 'https://flagcdn.com/w320/gw.png' },
    { name: 'Guyana', code: 'GY', dial_code: '+592', flag: '🇬🇾', image: 'https://flagcdn.com/w320/gy.png' },
    { name: 'Haiti', code: 'HT', dial_code: '+509', flag: '🇭🇹', image: 'https://flagcdn.com/w320/ht.png' },
    { name: 'Heard Island and McDonald Islands', code: 'HM', dial_code: '+672', flag: '🇭🇲', image: 'https://flagcdn.com/w320/hm.png' },
    { name: 'Vatican City', code: 'VA', dial_code: '+379', flag: '🇻🇦', image: 'https://flagcdn.com/w320/va.png' },
    { name: 'Honduras', code: 'HN', dial_code: '+504', flag: '🇭🇳', image: 'https://flagcdn.com/w320/hn.png' },
    { name: 'Hong Kong', code: 'HK', dial_code: '+852', flag: '🇭🇰', image: 'https://flagcdn.com/w320/hk.png' },
    { name: 'Hungary', code: 'HU', dial_code: '+36', flag: '🇭🇺', image: 'https://flagcdn.com/w320/hu.png' },
    { name: 'Iceland', code: 'IS', dial_code: '+354', flag: '🇮🇸', image: 'https://flagcdn.com/w320/is.png' },
    { name: 'India', code: 'IN', dial_code: '+91', flag: '🇮🇳', image: 'https://flagcdn.com/w320/in.png' },
    { name: 'Indonesia', code: 'ID', dial_code: '+62', flag: '🇮🇩', image: 'https://flagcdn.com/w320/id.png' },
    { name: 'Iran (Islamic Republic of)', code: 'IR', dial_code: '+98', flag: '🇮🇷', image: 'https://flagcdn.com/w320/ir.png' },
    { name: 'Iraq', code: 'IQ', dial_code: '+964', flag: '🇮🇶', image: 'https://flagcdn.com/w320/iq.png' },
    { name: 'Ireland', code: 'IE', dial_code: '+353', flag: '🇮🇪', image: 'https://flagcdn.com/w320/ie.png' },
    { name: 'Isle of Man', code: 'IM', dial_code: '+44', flag: '🇮🇲', image: 'https://flagcdn.com/w320/im.png' },
    { name: 'Israel', code: 'IL', dial_code: '+972', flag: '🇮🇱', image: 'https://flagcdn.com/w320/il.png' },
    { name: 'Italy', code: 'IT', dial_code: '+39', flag: '🇮🇹', image: 'https://flagcdn.com/w320/it.png' },
    { name: 'Jamaica', code: 'JM', dial_code: '+1876', flag: '🇯🇲', image: 'https://flagcdn.com/w320/jm.png' },
    { name: 'Japan', code: 'JP', dial_code: '+81', flag: '🇯🇵', image: 'https://flagcdn.com/w320/jp.png' },
    { name: 'Jersey', code: 'JE', dial_code: '+44', flag: '🇯🇪', image: 'https://flagcdn.com/w320/je.png' },
    { name: 'Jordan', code: 'JO', dial_code: '+962', flag: '🇯🇴', image: 'https://flagcdn.com/w320/jo.png' },
    { name: 'Kazakhstan', code: 'KZ', dial_code: '+7', flag: '🇰🇿', image: 'https://flagcdn.com/w320/kz.png' },
    { name: 'Kenya', code: 'KE', dial_code: '+254', flag: '🇰🇪', image: 'https://flagcdn.com/w320/ke.png' },
    { name: 'Kiribati', code: 'KI', dial_code: '+686', flag: '🇰🇮', image: 'https://flagcdn.com/w320/ki.png' },
    { name: 'Korea (Democratic People\'s Republic of)', code: 'KP', dial_code: '+850', flag: '🇰🇵', image: 'https://flagcdn.com/w320/kp.png' },
    { name: 'Korea (Republic of)', code: 'KR', dial_code: '+82', flag: '🇰🇷', image: 'https://flagcdn.com/w320/kr.png' },
    { name: 'Kosovo', code: 'XK', dial_code: '+383', flag: '🇽🇰', image: 'https://flagcdn.com/w320/xk.png' },
    { name: 'Kuwait', code: 'KW', dial_code: '+965', flag: '🇰🇼', image: 'https://flagcdn.com/w320/kw.png' },
    { name: 'Kyrgyzstan', code: 'KG', dial_code: '+996', flag: '🇰🇬', image: 'https://flagcdn.com/w320/kg.png' },
    { name: 'Lao People\'s Democratic Republic', code: 'LA', dial_code: '+856', flag: '🇱🇦', image: 'https://flagcdn.com/w320/la.png' },
    { name: 'Latvia', code: 'LV', dial_code: '+371', flag: '🇱🇻', image: 'https://flagcdn.com/w320/lv.png' },
    { name: 'Lebanon', code: 'LB', dial_code: '+961', flag: '🇱🇧', image: 'https://flagcdn.com/w320/lb.png' },
    { name: 'Lesotho', code: 'LS', dial_code: '+266', flag: '🇱🇸', image: 'https://flagcdn.com/w320/ls.png' },
    { name: 'Liberia', code: 'LR', dial_code: '+231', flag: '🇱🇷', image: 'https://flagcdn.com/w320/lr.png' },
    { name: 'Libya', code: 'LY', dial_code: '+218', flag: '🇱🇾', image: 'https://flagcdn.com/w320/ly.png' },
    { name: 'Liechtenstein', code: 'LI', dial_code: '+423', flag: '🇱🇮', image: 'https://flagcdn.com/w320/li.png' },
    { name: 'Lithuania', code: 'LT', dial_code: '+370', flag: '🇱🇹', image: 'https://flagcdn.com/w320/lt.png' },
    { name: 'Luxembourg', code: 'LU', dial_code: '+352', flag: '🇱🇺', image: 'https://flagcdn.com/w320/lu.png' },
    { name: 'Macao', code: 'MO', dial_code: '+853', flag: '🇲🇴', image: 'https://flagcdn.com/w320/mo.png' },
    { name: 'Macedonia (The former Yugoslav Republic of)', code: 'MK', dial_code: '+389', flag: '🇲🇰', image: 'https://flagcdn.com/w320/mk.png' },
    { name: 'Madagascar', code: 'MG', dial_code: '+261', flag: '🇲🇬', image: 'https://flagcdn.com/w320/mg.png' },
    { name: 'Malawi', code: 'MW', dial_code: '+265', flag: '🇲🇼', image: 'https://flagcdn.com/w320/mw.png' },
    { name: 'Malaysia', code: 'MY', dial_code: '+60', flag: '🇲🇾', image: 'https://flagcdn.com/w320/my.png' },
    { name: 'Maldives', code: 'MV', dial_code: '+960', flag: '🇲🇻', image: 'https://flagcdn.com/w320/mv.png' },
    { name: 'Mali', code: 'ML', dial_code: '+223', flag: '🇲🇱', image: 'https://flagcdn.com/w320/ml.png' },
    { name: 'Malta', code: 'MT', dial_code: '+356', flag: '🇲🇹', image: 'https://flagcdn.com/w320/mt.png' },
    { name: 'Marshall Islands', code: 'MH', dial_code: '+692', flag: '🇲🇭', image: 'https://flagcdn.com/w320/mh.png' },
    { name: 'Martinique', code: 'MQ', dial_code: '+596', flag: '🇲🇶', image: 'https://flagcdn.com/w320/mq.png' },
    { name: 'Mauritania', code: 'MR', dial_code: '+222', flag: '🇲🇷', image: 'https://flagcdn.com/w320/mr.png' },
    { name: 'Mauritius', code: 'MU', dial_code: '+230', flag: '🇲🇺', image: 'https://flagcdn.com/w320/mu.png' },
    { name: 'Mayotte', code: 'YT', dial_code: '+262', flag: '🇾🇹', image: 'https://flagcdn.com/w320/yt.png' },
    { name: 'Mexico', code: 'MX', dial_code: '+52', flag: '🇲🇽', image: 'https://flagcdn.com/w320/mx.png' },
    { name: 'Micronesia (Federated States of)', code: 'FM', dial_code: '+691', flag: '🇫🇲', image: 'https://flagcdn.com/w320/fm.png' },
    { name: 'Moldova (Republic of)', code: 'MD', dial_code: '+373', flag: '🇲🇩', image: 'https://flagcdn.com/w320/md.png' },
    { name: 'Monaco', code: 'MC', dial_code: '+377', flag: '🇲🇨', image: 'https://flagcdn.com/w320/mc.png' },
    { name: 'Mongolia', code: 'MN', dial_code: '+976', flag: '🇲🇳', image: 'https://flagcdn.com/w320/mn.png' },
    { name: 'Montenegro', code: 'ME', dial_code: '+382', flag: '🇲🇪', image: 'https://flagcdn.com/w320/me.png' },
    { name: 'Montserrat', code: 'MS', dial_code: '+1664', flag: '🇲🇸', image: 'https://flagcdn.com/w320/ms.png' },
    { name: 'Morocco', code: 'MA', dial_code: '+212', flag: '🇲🇦', image: 'https://flagcdn.com/w320/ma.png' },
    { name: 'Mozambique', code: 'MZ', dial_code: '+258', flag: '🇲🇿', image: 'https://flagcdn.com/w320/mz.png' },
    { name: 'Myanmar', code: 'MM', dial_code: '+95', flag: '🇲🇲', image: 'https://flagcdn.com/w320/mm.png' },
    { name: 'Namibia', code: 'NA', dial_code: '+264', flag: '🇳🇦', image: 'https://flagcdn.com/w320/na.png' },
    { name: 'Nauru', code: 'NR', dial_code: '+674', flag: '🇳🇷', image: 'https://flagcdn.com/w320/nr.png' },
    { name: 'Nepal', code: 'NP', dial_code: '+977', flag: '🇳🇵', image: 'https://flagcdn.com/w320/np.png' },
    { name: 'Netherlands', code: 'NL', dial_code: '+31', flag: '🇳🇱', image: 'https://flagcdn.com/w320/nl.png' },
    { name: 'New Caledonia', code: 'NC', dial_code: '+687', flag: '🇳🇨', image: 'https://flagcdn.com/w320/nc.png' },
    { name: 'New Zealand', code: 'NZ', dial_code: '+64', flag: '🇳🇿', image: 'https://flagcdn.com/w320/nz.png' },
    { name: 'Nicaragua', code: 'NI', dial_code: '+505', flag: '🇳🇮', image: 'https://flagcdn.com/w320/ni.png' },
    { name: 'Niger', code: 'NE', dial_code: '+227', flag: '🇳🇪', image: 'https://flagcdn.com/w320/ne.png' },
    { name: 'Nigeria', code: 'NG', dial_code: '+234', flag: '🇳🇬', image: 'https://flagcdn.com/w320/ng.png' },
    { name: 'Niue', code: 'NU', dial_code: '+683', flag: '🇳🇺', image: 'https://flagcdn.com/w320/nu.png' },
    { name: 'Norfolk Island', code: 'NF', dial_code: '+672', flag: '🇳🇫', image: 'https://flagcdn.com/w320/nf.png' },
    { name: 'Northern Mariana Islands', code: 'MP', dial_code: '+1670', flag: '🇲🇵', image: 'https://flagcdn.com/w320/mp.png' },
    { name: 'Norway', code: 'NO', dial_code: '+47', flag: '🇳🇴', image: 'https://flagcdn.com/w320/no.png' },
    { name: 'Oman', code: 'OM', dial_code: '+968', flag: '🇴🇲', image: 'https://flagcdn.com/w320/om.png' },
    { name: 'Pakistan', code: 'PK', dial_code: '+92', flag: '🇵🇰', image: 'https://flagcdn.com/w320/pk.png' },
    { name: 'Palau', code: 'PW', dial_code: '+680', flag: '🇵🇼', image: 'https://flagcdn.com/w320/pw.png' },
    { name: 'Palestine (State of)', code: 'PS', dial_code: '+970', flag: '🇵🇸', image: 'https://flagcdn.com/w320/ps.png' },
    { name: 'Panama', code: 'PA', dial_code: '+507', flag: '🇵🇦', image: 'https://flagcdn.com/w320/pa.png' },
    { name: 'Papua New Guinea', code: 'PG', dial_code: '+675', flag: '🇵🇬', image: 'https://flagcdn.com/w320/pg.png' },
    { name: 'Paraguay', code: 'PY', dial_code: '+595', flag: '🇵🇾', image: 'https://flagcdn.com/w320/py.png' },
    { name: 'Peru', code: 'PE', dial_code: '+51', flag: '🇵🇪', image: 'https://flagcdn.com/w320/pe.png' },
    { name: 'Philippines', code: 'PH', dial_code: '+63', flag: '🇵🇭', image: 'https://flagcdn.com/w320/ph.png' },
    { name: 'Pitcairn', code: 'PN', dial_code: '+64', flag: '🇵🇳', image: 'https://flagcdn.com/w320/pn.png' },
    { name: 'Poland', code: 'PL', dial_code: '+48', flag: '🇵🇱', image: 'https://flagcdn.com/w320/pl.png' },
    { name: 'Portugal', code: 'PT', dial_code: '+351', flag: '🇵🇹', image: 'https://flagcdn.com/w320/pt.png' },
    { name: 'Puerto Rico', code: 'PR', dial_code: '+1787', flag: '🇵🇷', image: 'https://flagcdn.com/w320/pr.png' },
    { name: 'Qatar', code: 'QA', dial_code: '+974', flag: '🇶🇦', image: 'https://flagcdn.com/w320/qa.png' },
    { name: 'Romania', code: 'RO', dial_code: '+40', flag: '🇷🇴', image: 'https://flagcdn.com/w320/ro.png' },
    { name: 'Réunion', code: 'RE', dial_code: '+262', flag: '🇷🇪', image: 'https://flagcdn.com/w320/re.png' },
    { name: 'Russian Federation', code: 'RU', dial_code: '+7', flag: '🇷🇺', image: 'https://flagcdn.com/w320/ru.png' },
    { name: 'Rwanda', code: 'RW', dial_code: '+250', flag: '🇷🇼', image: 'https://flagcdn.com/w320/rw.png' },
    { name: 'Saint Barthélemy', code: 'BL', dial_code: '+590', flag: '🇧🇱', image: 'https://flagcdn.com/w320/bl.png' },
    { name: 'Saint Helena, Ascension and Tristan da Cunha', code: 'SH', dial_code: '+290', flag: '🇸🇭', image: 'https://flagcdn.com/w320/sh.png' },
    { name: 'Saint Kitts and Nevis', code: 'KN', dial_code: '+1869', flag: '🇰🇳', image: 'https://flagcdn.com/w320/kn.png' },
    { name: 'Saint Lucia', code: 'LC', dial_code: '+1758', flag: '🇱🇨', image: 'https://flagcdn.com/w320/lc.png' },
    { name: 'Saint Martin (Collectivity of France)', code: 'MF', dial_code: '+590', flag: '🇲🇫', image: 'https://flagcdn.com/w320/mf.png' },
    { name: 'Saint Pierre and Miquelon', code: 'PM', dial_code: '+508', flag: '🇵🇲', image: 'https://flagcdn.com/w320/pm.png' },
    { name: 'Saint Vincent and the Grenadines', code: 'VC', dial_code: '+1784', flag: '🇻🇨', image: 'https://flagcdn.com/w320/vc.png' },
    { name: 'Samoa', code: 'WS', dial_code: '+685', flag: '🇼🇸', image: 'https://flagcdn.com/w320/ws.png' },
    { name: 'San Marino', code: 'SM', dial_code: '+378', flag: '🇸🇲', image: 'https://flagcdn.com/w320/sm.png' },
    { name: 'Sao Tome and Principe', code: 'ST', dial_code: '+239', flag: '🇸🇹', image: 'https://flagcdn.com/w320/st.png' },
    { name: 'Saudi Arabia', code: 'SA', dial_code: '+966', flag: '🇸🇦', image: 'https://flagcdn.com/w320/sa.png' },
    { name: 'Senegal', code: 'SN', dial_code: '+221', flag: '🇸🇳', image: 'https://flagcdn.com/w320/sn.png' },
    { name: 'Serbia', code: 'RS', dial_code: '+381', flag: '🇷🇸', image: 'https://flagcdn.com/w320/rs.png' },
    { name: 'Seychelles', code: 'SC', dial_code: '+248', flag: '🇸🇨', image: 'https://flagcdn.com/w320/sc.png' },
    { name: 'Sierra Leone', code: 'SL', dial_code: '+232', flag: '🇸🇱', image: 'https://flagcdn.com/w320/sl.png' },
    { name: 'Singapore', code: 'SG', dial_code: '+65', flag: '🇸🇬', image: 'https://flagcdn.com/w320/sg.png' },
    { name: 'Sint Maarten (Dutch Constituency)', code: 'SX', dial_code: '+1721', flag: '🇸🇽', image: 'https://flagcdn.com/w320/sx.png' },
    { name: 'Slovakia', code: 'SK', dial_code: '+421', flag: '🇸🇰', image: 'https://flagcdn.com/w320/sk.png' },
    { name: 'Slovenia', code: 'SI', dial_code: '+386', flag: '🇸🇮', image: 'https://flagcdn.com/w320/si.png' },
    { name: 'Solomon Islands', code: 'SB', dial_code: '+677', flag: '🇸🇧', image: 'https://flagcdn.com/w320/sb.png' },
    { name: 'Somalia', code: 'SO', dial_code: '+252', flag: '🇸🇴', image: 'https://flagcdn.com/w320/so.png' },
    { name: 'South Africa', code: 'ZA', dial_code: '+27', flag: '🇿🇦', image: 'https://flagcdn.com/w320/za.png' },
    { name: 'South Georgia and the South Sandwich Islands', code: 'GS', dial_code: '+500', flag: '🇬🇸', image: 'https://flagcdn.com/w320/gs.png' },
    { name: 'South Sudan', code: 'SS', dial_code: '+211', flag: '🇸🇸', image: 'https://flagcdn.com/w320/ss.png' },
    { name: 'Spain', code: 'ES', dial_code: '+34', flag: '🇪🇸', image: 'https://flagcdn.com/w320/es.png' },
    { name: 'Sri Lanka', code: 'LK', dial_code: '+94', flag: '🇱🇰', image: 'https://flagcdn.com/w320/lk.png' },
    { name: 'Sudan', code: 'SD', dial_code: '+249', flag: '🇸🇩', image: 'https://flagcdn.com/w320/sd.png' },
    { name: 'Suriname', code: 'SR', dial_code: '+597', flag: '🇸🇷', image: 'https://flagcdn.com/w320/sr.png' },
    { name: 'Svalbard and Jan Mayen', code: 'SJ', dial_code: '+47', flag: '🇸🇯', image: 'https://flagcdn.com/w320/sj.png' },
    { name: 'Swaziland', code: 'SZ', dial_code: '+268', flag: '🇸🇿', image: 'https://flagcdn.com/w320/sz.png' },
    { name: 'Sweden', code: 'SE', dial_code: '+46', flag: '🇸🇪', image: 'https://flagcdn.com/w320/se.png' },
    { name: 'Switzerland', code: 'CH', dial_code: '+41', flag: '🇨🇭', image: 'https://flagcdn.com/w320/ch.png' },
    { name: 'Syrian Arab Republic', code: 'SY', dial_code: '+963', flag: '🇸🇾', image: 'https://flagcdn.com/w320/sy.png' },
    { name: 'Taiwan (Republic of China)', code: 'TW', dial_code: '+886', flag: '🇹🇼', image: 'https://flagcdn.com/w320/tw.png' },
    { name: 'Tajikistan', code: 'TJ', dial_code: '+992', flag: '🇹🇯', image: 'https://flagcdn.com/w320/tj.png' },
    { name: 'Tanzania (United Republic of)', code: 'TZ', dial_code: '+255', flag: '🇹🇿', image: 'https://flagcdn.com/w320/tz.png' },
    { name: 'Thailand', code: 'TH', dial_code: '+66', flag: '🇹🇭', image: 'https://flagcdn.com/w320/th.png' },
    { name: 'Timor-Leste', code: 'TL', dial_code: '+670', flag: '🇹🇱', image: 'https://flagcdn.com/w320/tl.png' },
    { name: 'Togo', code: 'TG', dial_code: '+228', flag: '🇹🇬', image: 'https://flagcdn.com/w320/tg.png' },
    { name: 'Tokelau', code: 'TK', dial_code: '+690', flag: '🇹🇰', image: 'https://flagcdn.com/w320/tk.png' },
    { name: 'Tonga', code: 'TO', dial_code: '+676', flag: '🇹🇴', image: 'https://flagcdn.com/w320/to.png' },
    { name: 'Trinidad and Tobago', code: 'TT', dial_code: '+1868', flag: '🇹🇹', image: 'https://flagcdn.com/w320/tt.png' },
    { name: 'Tunisia', code: 'TN', dial_code: '+216', flag: '🇹🇳', image: 'https://flagcdn.com/w320/tn.png' },
    { name: 'Türkiye (Turkey)', code: 'TR', dial_code: '+90', flag: '🇹🇷', image: 'https://flagcdn.com/w320/tr.png' },
    { name: 'Turkmenistan', code: 'TM', dial_code: '+993', flag: '🇹🇲', image: 'https://flagcdn.com/w320/tm.png' },
    { name: 'Turks and Caicos Islands', code: 'TC', dial_code: '+1649', flag: '🇹🇨', image: 'https://flagcdn.com/w320/tc.png' },
    { name: 'Tuvalu', code: 'TV', dial_code: '+688', flag: '🇹🇻', image: 'https://flagcdn.com/w320/tv.png' },
    { name: 'Uganda', code: 'UG', dial_code: '+256', flag: '🇺🇬', image: 'https://flagcdn.com/w320/ug.png' },
    { name: 'Ukraine', code: 'UA', dial_code: '+380', flag: '🇺🇦', image: 'https://flagcdn.com/w320/ua.png' },
    { name: 'United Arab Emirates', code: 'AE', dial_code: '+971', flag: '🇦🇪', image: 'https://flagcdn.com/w320/ae.png' },
    { name: 'United Kingdom of Great Britain and Northern Ireland', code: 'GB', dial_code: '+44', flag: '🇬🇧', image: 'https://flagcdn.com/w320/gb.png' },
    { name: 'United States Minor Outlying Islands', code: 'UM', dial_code: '+1', flag: '🇺🇲', image: 'https://flagcdn.com/w320/um.png' },
    { name: 'United States of America', code: 'US', dial_code: '+1', flag: '🇺🇸', image: 'https://flagcdn.com/w320/us.png' },
    { name: 'Uruguay', code: 'UY', dial_code: '+598', flag: '🇺🇾', image: 'https://flagcdn.com/w320/uy.png' },
    { name: 'Uzbekistan', code: 'UZ', dial_code: '+998', flag: '🇺🇿', image: 'https://flagcdn.com/w320/uz.png' },
    { name: 'Vanuatu', code: 'VU', dial_code: '+678', flag: '🇻🇺', image: 'https://flagcdn.com/w320/vu.png' },
    { name: 'Venezuela (Bolivarian Republic of)', code: 'VE', dial_code: '+58', flag: '🇻🇪', image: 'https://flagcdn.com/w320/ve.png' },
    { name: 'Vietnam', code: 'VN', dial_code: '+84', flag: '🇻🇳', image: 'https://flagcdn.com/w320/vn.png' },
    { name: 'Virgin Islands (British)', code: 'VG', dial_code: '+1284', flag: '🇻🇬', image: 'https://flagcdn.com/w320/vg.png' },
    { name: 'Virgin Islands (U.S.)', code: 'VI', dial_code: '+1340', flag: '🇻🇮', image: 'https://flagcdn.com/w320/vi.png' },
    { name: 'Wallis and Futuna', code: 'WF', dial_code: '+681', flag: '🇼🇫', image: 'https://flagcdn.com/w320/wf.png' },
    { name: 'Western Sahara', code: 'EH', dial_code: '+212', flag: '🇪🇭', image: 'https://flagcdn.com/w320/eh.png' },
    { name: 'Yemen', code: 'YE', dial_code: '+967', flag: '🇾🇪', image: 'https://flagcdn.com/w320/ye.png' },
    { name: 'Zambia', code: 'ZM', dial_code: '+260', flag: '🇿🇲', image: 'https://flagcdn.com/w320/zm.png' },
    { name: 'Zimbabwe', code: 'ZW', dial_code: '+263', flag: '🇿🇼', image: 'https://flagcdn.com/w320/zw.png' }
];

export const paymentMethods = [
    {
        id: 'qr_code',
        title: 'QR Code',
        description: 'Customer scans a QR code to pay.',
    },
    {
        id: 'hosted_invoice',
        title: 'Hosted Invoice',
        description: 'Email your customer a payment link to pay later.',
    },
    {
        id: 'cash',
        title: 'Collect Cash',
        description: 'Record a cash payment made directly by the customer.',
    },
    {
        id: 'manual_transaction_id',
        title: 'Manual Transaction ID',
        description: 'Manually enter a Stripe transaction ID (pi_... or ch_...).'
    }
];
